// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC9l0eXtgzkkqDIN8f-CyST7AD-HPFdDU',
    appId: '1:546957608794:web:789e15e76d6466a9ce1563',
    messagingSenderId: '546957608794',
    projectId: 'devxecommerce',
    authDomain: 'devxecommerce.firebaseapp.com',
    storageBucket: 'devxecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1X1rZjeLOvpEnTw_wlOyOKLwjsK35yM',
    appId: '1:546957608794:android:34e4bf16d315d483ce1563',
    messagingSenderId: '546957608794',
    projectId: 'devxecommerce',
    storageBucket: 'devxecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA70u-aroO2_uJg_TIg71LwKM9BzOlXLBM',
    appId: '1:546957608794:ios:d16fed015b984d01ce1563',
    messagingSenderId: '546957608794',
    projectId: 'devxecommerce',
    storageBucket: 'devxecommerce.appspot.com',
    iosClientId: '546957608794-8nqum3q0ephb3e06s5vd1ujt72dehh14.apps.googleusercontent.com',
    iosBundleId: 'com.example.devxecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA70u-aroO2_uJg_TIg71LwKM9BzOlXLBM',
    appId: '1:546957608794:ios:17c4d0f4defcdd02ce1563',
    messagingSenderId: '546957608794',
    projectId: 'devxecommerce',
    storageBucket: 'devxecommerce.appspot.com',
    iosClientId: '546957608794-9bhpekdj5violdi5kbpqrap7nsk2m904.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxStandard.RunnerTests',
  );
}
